
package sdgsweden.admin;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import sdgsweden.MainFrame;
import sdgsweden.Startsida;
import oru.inf.InfException;
/**
 *
 * @author willi
 */
public class AdminPanel extends javax.swing.JPanel {

    private MainFrame parent;
    private InfDB idb;
    private String aid;
    
    public AdminPanel(MainFrame parent, InfDB idb, String aid) {
    this.parent = parent;
    this.idb = idb;
    this.aid = aid;
    initComponents();
}
    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFornamn = new javax.swing.JTextField();
        txtEfternamn = new javax.swing.JTextField();
        txtAdress = new javax.swing.JTextField();
        txtEpost = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAnstallningsdatum = new javax.swing.JTextField();
        pwdLosenord = new javax.swing.JPasswordField();
        txtAvdelning = new javax.swing.JTextField();
        btnLaggTillAnstalld = new javax.swing.JButton();
        btnGenereraLosenord = new javax.swing.JButton();
        chkVisaLosenord = new javax.swing.JCheckBox();
        btnTaBortAnstalld = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnRedigeraAvdelning = new javax.swing.JButton();
        btnRedigeraPartner = new javax.swing.JButton();
        btnRedigeraLand = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lägg till/Ta bort anställd"));

        jLabel1.setText("Förnamn*");

        jLabel2.setText("Efternamn*");

        jLabel3.setText("Adress*");

        jLabel4.setText("Epost*");

        jLabel5.setText("Telefon*");

        txtFornamn.setPreferredSize(new java.awt.Dimension(150, 24));

        txtEfternamn.setPreferredSize(new java.awt.Dimension(150, 24));

        txtAdress.setPreferredSize(new java.awt.Dimension(150, 24));

        txtEpost.setPreferredSize(new java.awt.Dimension(150, 24));

        txtTelefon.setPreferredSize(new java.awt.Dimension(150, 24));

        jLabel6.setText("Anställningsdatum (yyyy-MM-dd)*");

        jLabel7.setText("Lösenord (Dolt)*");

        jLabel8.setText("Avdelning (ID)*");

        txtAnstallningsdatum.setPreferredSize(new java.awt.Dimension(150, 24));

        pwdLosenord.setPreferredSize(new java.awt.Dimension(150, 24));

        txtAvdelning.setPreferredSize(new java.awt.Dimension(150, 24));

        btnLaggTillAnstalld.setText("Lägg till");
        btnLaggTillAnstalld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillAnstalldActionPerformed(evt);
            }
        });

        btnGenereraLosenord.setText("Generera lösenord");
        btnGenereraLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenereraLosenordActionPerformed(evt);
            }
        });

        chkVisaLosenord.setText("Visa lösenord");
        chkVisaLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVisaLosenordActionPerformed(evt);
            }
        });

        btnTaBortAnstalld.setText("Ta bort");
        btnTaBortAnstalld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortAnstalldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwdLosenord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAvdelning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnstallningsdatum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGenereraLosenord)
                            .addComponent(btnTaBortAnstalld)
                            .addComponent(chkVisaLosenord)
                            .addComponent(btnLaggTillAnstalld))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAnstallningsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pwdLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnLaggTillAnstalld)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTaBortAnstalld)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenereraLosenord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkVisaLosenord)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Redigera enhet"));

        btnRedigeraAvdelning.setText("Avdelning");
        btnRedigeraAvdelning.setPreferredSize(new java.awt.Dimension(150, 24));
        btnRedigeraAvdelning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedigeraAvdelningActionPerformed(evt);
            }
        });

        btnRedigeraPartner.setText("Partner");
        btnRedigeraPartner.setPreferredSize(new java.awt.Dimension(150, 24));
        btnRedigeraPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedigeraPartnerActionPerformed(evt);
            }
        });

        btnRedigeraLand.setText("Land");
        btnRedigeraLand.setPreferredSize(new java.awt.Dimension(150, 24));
        btnRedigeraLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedigeraLandActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRedigeraLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRedigeraPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRedigeraAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTillbaka)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnRedigeraAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRedigeraPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRedigeraLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTillbaka)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenereraLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenereraLosenordActionPerformed
        String tecken = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()-_=+[]{}|;:,.<>?/~";

        //Detta betyder att den kan generera ett lösenord som inenhåller bokstäver mellan a-z (Stora och små bokstäver) samt siffrorna 0-9 och tecken.
        
        StringBuilder losenord = new StringBuilder();
        //Här skapas ett tomt objekt av typen "StringBuilder". Går att använda "String" också men "StringBuilder" anses som ett bättre val gällande kommande for-loop.
        
        for (int i = 0; i < 11; i++)
        //Detta är en for-loop som beskriver att loopen körs 10 gånger vilket också innebär att lösenordet är 10 tecken långt.
        {
            int index = (int)(Math.random() * tecken.length());
            //Raden ovan väljer ett slumpmässigt tal som visar vilket tal och/eller tecken som ska väljas från "String tecken".
            //Math.random() genererar ett slumpmässigt tal mellan 0 och 1.
            //tecken.length() = Hur många tecken som finns i "String tecken".
            //(int) = Detta tar bort decimalerna vilekt bidrar till att lösenordet blir av heltal.
            
            losenord.append(tecken.charAt(index));
            //Här hämtar vi ett tecken från "String tecken" på platsen "index" och lägger det i lösenordet.
        }
        pwdLosenord.setText(losenord.toString());
        //Losenord.toString() = omvandlar "StringBuilder" till en textsträng.
        //setText = Gör att lösenordet visas i textfältet.
               

    }//GEN-LAST:event_btnGenereraLosenordActionPerformed

    private void chkVisaLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVisaLosenordActionPerformed
        if (chkVisaLosenord.isSelected())
        //En if-sats där det här kontrolleras om rutan är ikryssad.
        {
            pwdLosenord.setEchoChar((char) 0);
            //Sista stycket i denna rad säger att lösenordet ska visas i vanlig text.
        }
        else
        //Detta körs om inte rutan är ikryssad.
        {
            pwdLosenord.setEchoChar('•');
            //Lösenordet visas isåfall i denna formen "•••••".
        }
    

    }//GEN-LAST:event_chkVisaLosenordActionPerformed

    private void btnRedigeraAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedigeraAvdelningActionPerformed
    AdminAvdelning adminAvdelningPanel = new AdminAvdelning(parent, idb, aid);
    parent.visaPanel(adminAvdelningPanel, "adminAvdelning");
        
        
    }//GEN-LAST:event_btnRedigeraAvdelningActionPerformed

    private void btnRedigeraPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedigeraPartnerActionPerformed
        AdminPartner adminPartnerPanel = new AdminPartner(parent, idb, aid);
        parent.visaPanel(adminPartnerPanel, "adminPartner");
    }//GEN-LAST:event_btnRedigeraPartnerActionPerformed

    private void btnRedigeraLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedigeraLandActionPerformed
        AdminLand adminLandPanel = new AdminLand(parent, idb, aid);
        parent.visaPanel(adminLandPanel, "adminLand");
    }//GEN-LAST:event_btnRedigeraLandActionPerformed

    private void btnLaggTillAnstalldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillAnstalldActionPerformed
        try {
        // Hämta alla värden från formuläret
        String fornamn = txtFornamn.getText().trim();
        String efternamn = txtEfternamn.getText().trim();
        String adress = txtAdress.getText().trim();
        String epost = txtEpost.getText().trim();
        String telefon = txtTelefon.getText().trim();
        String datum = txtAnstallningsdatum.getText().trim();
        String losenord = new String(pwdLosenord.getPassword()).trim();
        String avdelningStr = txtAvdelning.getText().trim();

        // Kontroll: tomma fält
        if (fornamn.isEmpty() || efternamn.isEmpty() || adress.isEmpty() || epost.isEmpty() ||
            telefon.isEmpty() || datum.isEmpty() || losenord.isEmpty() || avdelningStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fyll i alla fält.");
            return;
        }

        // Kontroll: epost-format
        if (!epost.matches("^[a-zA-Z]+\\.[a-zA-Z]+@example\\.com$")) {
            JOptionPane.showMessageDialog(this, "E-postadressen måste vara i formatet fornamn.efternamn@example.com");
            return;
        }

        // Kontroll: datumformat
        try {
            java.time.LocalDate.parse(datum); // Format: YYYY-MM-DD
        } catch (java.time.format.DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Datumet måste vara i formatet YYYY-MM-DD.");
            return;
        }

        // Konvertera avdelning till int
        int avdelning = Integer.parseInt(avdelningStr);

        // Hämta nästa lediga aid
        String sqlNextId = "SELECT MAX(aid) + 1 FROM anstalld";
        String nextIdStr = idb.fetchSingle(sqlNextId);
        if (nextIdStr == null) {
            nextIdStr = "1";
        }
        int nextAid = Integer.parseInt(nextIdStr);

        // Skapa INSERT-fråga
        String sql = "INSERT INTO anstalld (aid, fornamn, efternamn, adress, epost, telefon, anstallningsdatum, losenord, avdelning) "
                   + "VALUES (" + nextAid + ", "
                   + "'" + fornamn + "', "
                   + "'" + efternamn + "', "
                   + "'" + adress + "', "
                   + "'" + epost + "', "
                   + "'" + telefon + "', "
                   + "'" + datum + "', "
                   + "'" + losenord + "', "
                   + avdelning + ")";

        // Kör INSERT
        idb.insert(sql);

        JOptionPane.showMessageDialog(this, "Anställd har lagts till i systemet!");

        // Rensa fält
        txtFornamn.setText("");
        txtEfternamn.setText("");
        txtAdress.setText("");
        txtEpost.setText("");
        txtTelefon.setText("");
        txtAnstallningsdatum.setText("");
        pwdLosenord.setText("");
        txtAvdelning.setText("");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Fel: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnLaggTillAnstalldActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        Startsida startsida = new Startsida(parent, idb, aid);
        parent.visaPanel(startsida, "startsida");
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnTaBortAnstalldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortAnstalldActionPerformed
        
        //Här påbörjar vi en try-catch sats. All kod mellan try och catch kommer nu köras.
        try
        {
            //Detta visar en popup-ruta som dyker upp efter man klickat på "Ta bort" och här får man ange "aid" för att ta bort en anställd.
            String anstalldId = JOptionPane.showInputDialog(this, "Ange anställnings-ID (aid) för att ta bort:");

            //Om man inte fyller i rutan med ett giltigt aid så kommer meddelandet i koden här under att visas.
            if (anstalldId.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Fyll i ett anställnings-ID först.");
                return;
            }

    // Hämta specifik information om den anställde.
    String sql = "SELECT fornamn, efternamn FROM anstalld WHERE aid = " + anstalldId;

    //Här körs SQL_frågan mot databasen.
    ArrayList<HashMap<String, String>> anstallda = idb.fetchRows(sql);

    //Om inget resultat hittas så kommer nedan meddelande att visas och sedan avbryts sekvensen på grund av "return".
    if (anstallda == null || anstallda.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Det finns ingen anställd med detta ID.");
        return;
    }

    // Lista namn (tekniskt sett en person, men vi håller samma struktur)
    String[] anstalldNamnLista = new String[anstallda.size()];
    for (int i = 0; i < anstallda.size(); i++) {
        anstalldNamnLista[i] = anstallda.get(i).get("fornamn") + " " + anstallda.get(i).get("efternamn");
    }

    // Dialog för att bekräfta borttagning
    String valdAnstalld = (String) JOptionPane.showInputDialog(
        this,
        "Bekräfta vilken anställd du vill ta bort:",
        "Ta bort anställd",
        JOptionPane.QUESTION_MESSAGE,
        null,
        anstalldNamnLista,
        anstalldNamnLista[0]
    );

    if (valdAnstalld != null) {
        for (HashMap<String, String> a : anstallda) {
            String namn = a.get("fornamn") + " " + a.get("efternamn");
            if (namn.equals(valdAnstalld)) {
                String deleteSql = "DELETE FROM anstalld WHERE aid = " + anstalldId;
                idb.delete(deleteSql);
                JOptionPane.showMessageDialog(this, "Den anställde togs bort.");
                break;
            }
        }
    }
} catch (InfException e) {
    JOptionPane.showMessageDialog(this, "Fel vid borttagning av anställd: " + e.getMessage());
}
    
    }//GEN-LAST:event_btnTaBortAnstalldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenereraLosenord;
    private javax.swing.JButton btnLaggTillAnstalld;
    private javax.swing.JButton btnRedigeraAvdelning;
    private javax.swing.JButton btnRedigeraLand;
    private javax.swing.JButton btnRedigeraPartner;
    private javax.swing.JButton btnTaBortAnstalld;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JCheckBox chkVisaLosenord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField pwdLosenord;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtAnstallningsdatum;
    private javax.swing.JTextField txtAvdelning;
    private javax.swing.JTextField txtEfternamn;
    private javax.swing.JTextField txtEpost;
    private javax.swing.JTextField txtFornamn;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
