/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
       
package sdgsweden;

import oru.inf.InfDB;

//Följande import`s är nödvändiga:
//1, importerar klassen för att skapa en anslutning till en databas.
//2, Gör det möjligt att etablera databasanslutning via JDBC.
//3, Skickar parametriserade SQL-frågor. Säkrare än att bygga strängar.
//4, Gör det möjligt att läsa resultatet av SQL-fråga.
//5, "Gör" att popup rutor eller JOptionsPane visas, Tex när vi loggar in.
import java.sql.Connection; 
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author wilhe
 */
public class Inloggning extends javax.swing.JFrame {

    /**
     * Creates new form Inloggning
     */
    public Inloggning(InfDB idb) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        PasswordField = new javax.swing.JPasswordField();
        TextFieldEpost = new javax.swing.JTextField();
        ButtonLoggaIn = new javax.swing.JButton();
        LabelRubrik = new javax.swing.JLabel();
        CheckBoxVisaLosenord = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        LabelEpost = new javax.swing.JLabel();
        LabelLosenord = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PasswordField.setColumns(11);

        TextFieldEpost.setColumns(10);

        ButtonLoggaIn.setText("Logga in");
        ButtonLoggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoggaInActionPerformed(evt);
            }
        });

        LabelRubrik.setText("Inloggning  SDG Sweden");

        CheckBoxVisaLosenord.setText("Visa Lösenord");
        CheckBoxVisaLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxVisaLosenordActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sdgsweden/bilder/använd.jpg"))); // NOI18N

        LabelEpost.setText("E-post:");

        LabelLosenord.setText("Lösenord:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(ButtonLoggaIn)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PasswordField)
                    .addComponent(TextFieldEpost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckBoxVisaLosenord)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEpost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelLosenord)
                    .addComponent(CheckBoxVisaLosenord))
                .addGap(18, 18, 18)
                .addComponent(ButtonLoggaIn)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBoxVisaLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxVisaLosenordActionPerformed
       if (CheckBoxVisaLosenord.isSelected()) {
    PasswordField.setEchoChar((char) 0); // Visa text
} else {
    PasswordField.setEchoChar('•'); // Dölj text
}

    }//GEN-LAST:event_CheckBoxVisaLosenordActionPerformed

    private void ButtonLoggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoggaInActionPerformed
        String epost = TextFieldEpost.getText();
String losenord = new String(PasswordField.getPassword());

try {
    // Ansluter till databas
    Connection conn = DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/sdgsweden", // vår databas
        "dbAdmin2024",                           // användarnamn
        "dbAdmin2024PW"                          //  MySQL-lösenord
    );

    // SQL-fråga med placeholders för att undvika SQL injection
    String sql = "SELECT * FROM anstalld WHERE epost = ? AND losenord = ?";
    PreparedStatement stmt = conn.prepareStatement(sql);
    stmt.setString(1, epost); // Vårt "användarnamn"
    stmt.setString(2, losenord); // Lösenord

    ResultSet rs = stmt.executeQuery();

    if (rs.next()) {
        String fornamn = rs.getString("fornamn");
        String efternamn = rs.getString("efternamn");
        
        JOptionPane.showMessageDialog(this, "Välkommen " + fornamn + " "+ efternamn + " ! Du kommer nu att logga in");

        // Öppna nästa fönster
        new ProgramFonster().setVisible(true);
        this.dispose(); // Stänger login-fönstret
    } else {
        //  Fel uppgifter
        JOptionPane.showMessageDialog(this, "Fel e-post eller lösenord.");
    }

    rs.close();
    stmt.close();
    conn.close();

} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Fel vid anslutning till databasen.");
}

    }//GEN-LAST:event_ButtonLoggaInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Inloggning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLoggaIn;
    private javax.swing.JCheckBox CheckBoxVisaLosenord;
    private javax.swing.JLabel LabelEpost;
    private javax.swing.JLabel LabelLosenord;
    private javax.swing.JLabel LabelRubrik;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField TextFieldEpost;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
