/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sdgsweden;

import oru.inf.InfDB;

//Följande import`s är nödvändiga:
//1, importerar klassen för att skapa en anslutning till en databas.
//2, Gör det möjligt att etablera databasanslutning via JDBC.
//3, Skickar parametriserade SQL-frågor. Säkrare än att bygga strängar.
//4, Gör det möjligt att läsa resultatet av SQL-fråga.
//5, "Gör" att popup rutor eller JOptionsPane visas, Tex när vi loggar in.
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Kalkilm: Nedan följer kod som tillåter användare att logga in i vårt
 * system baserat på data hämtat ur databasen, efter inloggningen lyckats så
 * plockar den med "aid" för att kunna fortsätta hålla kopplingen individuell.
 */
public class Inloggning extends javax.swing.JFrame {

    private InfDB idb;

    /**
     * Creates new form Inloggning
     */
    public Inloggning(InfDB idb) {
        this.idb = idb;
        initComponents();
    }

    public Inloggning() //extra klass för att få Logga ut att köra.
    {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        PasswordField = new javax.swing.JPasswordField();
        TextFieldEpost = new javax.swing.JTextField();
        ButtonLoggaIn = new javax.swing.JButton();
        LabelRubrik = new javax.swing.JLabel();
        CheckBoxVisaLosenord = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        LabelEpost = new javax.swing.JLabel();
        LabelLosenord = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PasswordField.setColumns(11);
        PasswordField.setText("passwordabc");

        TextFieldEpost.setColumns(10);
        TextFieldEpost.setText("sofia.a@example.com");
        TextFieldEpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldEpostActionPerformed(evt);
            }
        });

        ButtonLoggaIn.setText("Logga in");
        ButtonLoggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoggaInActionPerformed(evt);
            }
        });

        LabelRubrik.setText("Inloggning  SDG Sweden");

        CheckBoxVisaLosenord.setText("Visa Lösenord");
        CheckBoxVisaLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxVisaLosenordActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sdgsweden/bilder/använd.jpg"))); // NOI18N

        LabelEpost.setText("E-post:");

        LabelLosenord.setText("Lösenord:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(ButtonLoggaIn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelEpost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelLosenord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CheckBoxVisaLosenord)
                    .addComponent(TextFieldEpost)
                    .addComponent(PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelEpost)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextFieldEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelLosenord))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBoxVisaLosenord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(ButtonLoggaIn)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBoxVisaLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxVisaLosenordActionPerformed
        if (CheckBoxVisaLosenord.isSelected()) {
            PasswordField.setEchoChar((char) 0); //Visa text
        } else {
            PasswordField.setEchoChar('•'); //Dölj text med karaktär
        }

    }//GEN-LAST:event_CheckBoxVisaLosenordActionPerformed

    private void ButtonLoggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoggaInActionPerformed
        String epost = TextFieldEpost.getText();
        String losenord = new String(PasswordField.getPassword());

        try {

            // SQL-fråga med placeholders för att undvika SQL injection
            String sql = "SELECT * FROM anstalld WHERE epost = '" + epost + "' AND losenord = '" + losenord + "'";
            HashMap<String, String> user = idb.fetchRow(sql);

            //kontrollerear om objektet "user" faktiskt har ett värde.
            if (user != null) {
                String aid = user.get("aid"); //Hämntar värdet som är kopplat till nyckeln "aid" från HasMap User.
                String fornamn = user.get("fornamn"); //Hämtar värdet från nyckeln "fornman"
                String efternamn = user.get("efternamn"); //Hämntar värdet från nyckeln "efternamn"

                //Om användare finns i databasen och gör en lyckad inloggning visas ett fönster med följande text.
                JOptionPane.showMessageDialog(this, "Välkommen " + fornamn + " " + efternamn + " ! Du kommer nu att logga in");

                MainFrame main = new MainFrame(idb, aid); //Öppna nästa fönster
                main.setVisible(true);
                this.dispose(); //Stänger login-fönstret
            } else {
                // Fel uppgifter har angivits, intresenten tillåts inte att logga in.
                JOptionPane.showMessageDialog(this, "Fel e-post eller lösenord.");
            }

//Detta är ett felhanteringsblock som fångar upp eventuella fel som kan inteffa
        } catch (Exception ex) { //fångar alla fel av typen "exception"
            ex.printStackTrace(); //skriver ut en detaljerad felrapport till konsolen
            JOptionPane.showMessageDialog(this, "Fel vid anslutning till databasen.");//visar ett felmeddelandecför användaren i ett popup-fönster.
        }

    }//GEN-LAST:event_ButtonLoggaInActionPerformed

    private void TextFieldEpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldEpostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldEpostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Inloggning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLoggaIn;
    private javax.swing.JCheckBox CheckBoxVisaLosenord;
    private javax.swing.JLabel LabelEpost;
    private javax.swing.JLabel LabelLosenord;
    private javax.swing.JLabel LabelRubrik;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField TextFieldEpost;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
