
package sdgsweden;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import oru.inf.InfDB;
import oru.inf.InfException;

// MainFrame ärver klassen JFrame från java
    public class MainFrame extends javax.swing.JFrame {
    private InfDB idb;
    private String aid;
    
//Konstruktorn tar emot databasanslutningen och användarID på den inloggade personen.
    public MainFrame(InfDB idb, String aid) {
    this.idb = idb;
    this.aid = aid;
    initComponents();

   
    Startsida startsida = new Startsida(this, idb, aid);
    mainPanel.add(startsida, "startsida");

    CardLayout cl = (CardLayout) mainPanel.getLayout();
    cl.show(mainPanel, "startsida");
}

    
 //Gamla konstrukorn, används bara om man vill starta direkt från MainFrame istället för Inloggningsrutan.
    public MainFrame() {
         initComponents();
        try {
        InfDB idb = new InfDB ("sdgsweden", "3306", "dbAdmin2024", "dbAdmin2024PW");
        Startsida startsida = new Startsida(this, idb, aid);
        mainPanel.add(startsida, "startsida");

        // Visa startsidan som första vy
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "startsida");
        }
        catch (InfException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Kunde inte ansluta till databasen: " + ex.getMessage());
        }
    }
 // Metoden som används av andra klasser för att byta sida som visas i MainFrame-fönstret
    public void visaPanel(javax.swing.JPanel panel, String namn) {
        mainPanel.add(panel, namn);
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel,namn);
    }
    
    
// Kod från designläget
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());

                // Anpassade Nimbus-färger
                UIManager.put("control", new Color(240, 240, 255));
                UIManager.put("info", new Color(200, 200, 255));
                UIManager.put("nimbusBase", new Color(60, 120, 180));
                UIManager.put("nimbusBlueGrey", new Color(180, 200, 220));
                UIManager.put("text", Color.BLACK);
                UIManager.put("nimbusSelectionBackground", new Color(120, 180, 255));

                break;
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    // Skapa och visa GUI:t
    java.awt.EventQueue.invokeLater(() -> {
        new MainFrame().setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
