/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sdgsweden;
import oru.inf.InfDB;
import sdgsweden.projekt.Projekt;

/**
 *
 * @author User
 */
public class Startsida extends javax.swing.JPanel {
private MainFrame parent;
private InfDB idb;
private String aid;
    
    /**
     * Creates new form Startsida
     * @param parent
     */
    public Startsida(MainFrame parent,InfDB idb, String aid) {
            this.parent = parent;
            this.idb=idb;
            this.aid = aid;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProjekt = new javax.swing.JButton();
        label1 = new java.awt.Label();
        btnMittKonto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        btnProjekt.setText("Projekt");
        btnProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjektActionPerformed(evt);
            }
        });

        label1.setText("STARTSIDA");

        btnMittKonto.setText("Mitt Konto");
        btnMittKonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMittKontoActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. Ingen fattigdom", "2. Ingen hunger", "3. God hälsa och Välbefinnande", "4. God utbildning", "5. Jämställdhet", "6. Rent vatten och sanitet", "7. Hållbar energi för alla", "8. Anständiga arbetsvillkor och ekonomisk tillväxt", "9. Hållbar industri innovation och infrastruktur", "10. Minskad ojämlikhet", "11. Hållbara städer och samhällen", "12. Hållbar konsumtion och produktion", "13. Bekämpa klimatförändringar", "14. Hav och marina resurser", "15. Ekosystem och biologisk mångfald", "16. Fredliga och inkluderande samhällen", "17. Genomförande och globalt partnerskap" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnProjekt))
                            .addComponent(btnMittKonto))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(702, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnProjekt)
                        .addGap(27, 27, 27)
                        .addComponent(btnMittKonto))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(526, Short.MAX_VALUE))
        );

        label1.getAccessibleContext().setAccessibleName("Startsida");
    }// </editor-fold>//GEN-END:initComponents

    private void btnProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjektActionPerformed
    Projekt projektPanel = new Projekt(parent, idb,aid); // Skapa projektpanelen
    parent.visaPanel(projektPanel, "projekt"); // Visa den i MainFrame
    }//GEN-LAST:event_btnProjektActionPerformed

    private void btnMittKontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMittKontoActionPerformed
        // TODO add your handling code here:
        MittKonto mittKontoPanel = new MittKonto(idb, aid);
        parent.visaPanel(mittKontoPanel, "mittkonto");

    }//GEN-LAST:event_btnMittKontoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMittKonto;
    private javax.swing.JButton btnProjekt;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
